### ISSUE TITLE
Invalid IP addresses

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds-statistics#2]
```
Exception on /stats/ [GET]
Traceback (most recent call last):
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "./pybossa/view/stats.py", line 52, in index
    locs = site_stats.get_locs()
  File "./pybossa/cache/__init__.py", line 87, in wrapper
    output = f(*args, **kwargs)
  File "./pybossa/cache/site_stats.py", line 137, in get_locs
    loc = gic.record_by_addr(row.user_ip)
  File "/var/www/pybossa/env/local/lib/python2.7/site-packages/pygeoip/__init__.py", line 546, in record_by_addr
    ipnum = util.ip2long(addr)
  File "/var/www/pybossa/env/local/lib/python2.7/site-packages/pygeoip/util.py", line 39, in ip2long
    return int(binascii.hexlify(socket.inet_pton(socket.AF_INET6, ip)), 16)
error: illegal IP address string passed to inet_pton
```

**Comment by alexandermendes** [comment]
Not actually an issue with this plugin
